language: go
sudo: false

addons:
        apt:
                packages:
                        - libpcsclite-dev

os:
        - linux
        - osx

go:
        - 1.5
        - 1.6
        - 1.7
        - tip
